# This is a basic workflow to help you get started with Actions

name: Release Build

# Controls when the action will run. 
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build ${{ matrix.build_type }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - gradle_arg: "./gradlew assembleRelease"
            build_type: APK
            final_path: app/build/outputs/apk/release/app-release-unsigned.apk
            final_name: OpenMic_Client.apk
          - gradle_arg: "./gradlew bundleRelease"
            build_type: Bundle
            final_path: app/build/outputs/bundle/release/app-release.aab
            final_name: OpenMic_Client.aab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: ${{ matrix.gradle_arg }}
      
      - name: Move output to final destination
        run: |
          mkdir final
          cp ${{ matrix.final_path }} final/
      
      - uses: r0adkll/sign-android-release@v1
        name: Sign Build
        # ID used to access action output
        id: sign
        with:
          releaseDirectory: final/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign.outputs.signedReleaseFile}}
          asset_name: ${{ matrix.final_name }}
          tag: ${{ github.ref }}
          overwrite: true
      
