# This is a basic workflow to help you get started with Actions

name: Release Build

# Controls when the action will run. 
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Android Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build APK
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleRelease"
      
      - name: Build bundle
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew bundleRelease"
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        # ID used to access action output
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign Bundle
        # ID used to access action output
        id: sign_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_apk.outputs.signedReleaseFile}}
          asset_name: OpenMic_Client.apk
          tag: ${{ github.ref }}
          overwrite: true
      
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_bundle.outputs.signedReleaseFile}}
          asset_name: OpenMic_Client.aab
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Bundle to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: DistributionKit/InstallerOpenMic_Server.run
          asset_name: OpenMic_Linux_Setup_amd64.run
          tag: ${{ github.ref }}
          overwrite: true
