# This is a basic workflow to help you get started with Actions

name: Debug Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build ${{ matrix.build_type }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - gradle_arg: "./gradlew assembleDebug"
            build_type: APK
            final_path: app/build/outputs/apk/debug/app-debug.apk
          - gradle_arg: "./gradlew bundleDebug"
            build_type: Bundle
            final_path: app/build/outputs/bundle/debug/app-debug.aab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: ${{ matrix.gradle_arg }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{ matrix.build_type }}
          path: ${{ matrix.final_path }}
